src/Entity/Run.php
<?php

namespace App\Entity;

use App\Repository\RunRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\JoinTable;

#[ORM\Entity(repositoryClass: RunRepository::class)]
class Run
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(length: 255)]
    private ?string $map = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $run_date = null;

    #[ORM\ManyToMany(targetEntity: Runner::class, inversedBy: 'run')]
    private Collection $runner;

    #[ORM\OneToMany(mappedBy: 'run', targetEntity: RunJoinRequest::class, orphanRemoval: true)]
    private Collection $runJoinRequests;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $finished_at = null;

    public function __construct()
    {
        $this->runner = new ArrayCollection();
        $this->created_at = new \DateTimeImmutable();
        $this->runJoinRequests = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getMap(): ?string
    {
        return $this->map;
    }

    public function setMap(string $map): self
    {
        $this->map = $map;

        return $this;
    }

    public function getRunDate(): ?\DateTimeInterface
    {
        return $this->run_date;
    }

    public function setRunDate(\DateTimeInterface $run_date): self
    {
        $this->run_date = $run_date;

        return $this;
    }

    /**
     * @return Collection<int, runner>
     */
    public function getRunners(): Collection
    {
        return $this->runner;
    }

    public function addRunner(Runner $runner): self
    {
        if (!$this->runner->contains($runner)) {
            $this->runner->add($runner);
        }

        return $this;
    }

    public function removeRunner(Runner $runner): self
    {
        $this->runner->removeElement($runner);

        return $this;
    }

    /**
     * @return Collection<int, RunJoinRequest>
     */
    public function getRunJoinRequests(): Collection
    {
        return $this->runJoinRequests;
    }

    public function addRunJoinRequest(RunJoinRequest $runJoinRequest): self
    {
        if (!$this->runJoinRequests->contains($runJoinRequest)) {
            $this->runJoinRequests->add($runJoinRequest);
            $runJoinRequest->setRun($this);
        }

        return $this;
    }

    public function removeRunJoinRequest(RunJoinRequest $runJoinRequest): self
    {
        if ($this->runJoinRequests->removeElement($runJoinRequest)) {
            // set the owning side to null (unless already changed)
            if ($runJoinRequest->getRun() === $this) {
                $runJoinRequest->setRun(null);
            }
        }

        return $this;
    }

    public function getFinishedAt(): ?\DateTimeImmutable
    {
        return $this->finished_at;
    }

    public function setFinishedAt(?\DateTimeImmutable $finished_at): self
    {
        $this->finished_at = $finished_at;

        return $this;
    }
}

src/Controller/MapController.php
<?php

namespace App\Controller;

use App\Entity\Run;
use App\Repository\CoordinatesRepository;
use App\Repository\RunRepository;
use App\Service\ToolboxService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class MapController extends AbstractController
{
    #[Route('/', name: 'app_map_index')]
    public function index(RunRepository $runRepository): Response
    {
        return $this->render('map/home.html.twig', [
            //if there is no latest, return null
            'run' =>  (isset($runRepository->findLatest()[0])) ? $runRepository->findLatest()[0] : null,
            'upcomingRuns' => $runRepository->findUpcomingRuns(),
            'pastRuns' => $runRepository->findPastRuns()
        ]);
    }
    
    #[Route('/map/{id}', name: 'app_map_id')]
    public function run(RunRepository $runRepository, $id = null): Response
    {   
        //if there is no latest run -> redirect to index
        if (!isset($runRepository->findLatest()[0]) && $id == null) {
            return $this->redirectToRoute('app_map_index');
        }

        return $this->render('map/show.html.twig', [
            'run' => ($id) ? $runRepository->find($id) : $runRepository->findLatest()[0]
        ]);
    }

    #[Route('/coords/{id}/{timestamp}', name: 'app_map_coords')]
    public function coords(Run $run, CoordinatesRepository $coordinatesRepository, ToolboxService $toolboxService, $timestamp): Response
    {
        $response = new Response();
        $response->headers->set('Content-Type', 'application/json');
        $runners = array();
        foreach ($run->getRunners() as $runner) {
            $coords = array();
            foreach ($coordinatesRepository->findBy(["run" => $run, "runner" => $runner]) as $coord) {
                array_push($coords, ["latitude" => $coord->getLatitude(), "longitude" => $coord->getLongitude(), "date" => $coord->getCoordsDate()->format('U')]);
            }
            array_push($runners, ["runner" => ["login" => $runner->getLogin(), "picture" => $runner->getPicture(), "id" => $runner->getId()],  "coords" => $toolboxService->find_closest($coords, $timestamp)]);
        }
        $response->setContent(json_encode($runners));
        return $response;
    }
}

templates/map/home.html.twig
{% block body %}
    {% block map %}
        {% include 'map/index.html.twig' %}
    {% endblock %}
{% endblock %}

templates/map/index.html.twig
{% extends 'map.html.twig' %}
{% block stylesheets %}
	<link rel="stylesheet" href="{{ asset("assets/css/index.css") }}">
	<link rel="stylesheet" href="{{ asset("assets/css/font.css") }}">
	<link rel="stylesheet" href="{{ asset("assets/css/base.css") }}">
	<link rel="stylesheet" href="{{ asset("assets/css/navbar.css") }}">
{% endblock %}

{% block javascripts %}
	<script src="https://kit.fontawesome.com/faa5ea95e9.js" crossorigin="anonymous"></script>
	<script src="{{ asset("assets/js/navbar.js") }}"></script>
	<script src="{{ asset("assets/js/openMap.js") }}"></script>
	{% if run %}
		<script>
			const Run = {
				id: {{run.id}}, name: "{{run.name}}", created_at: {{run.createdAt|date('U')}}, map: "{{run.map}}", date: {{run.runDate|date('U')}}, finished_at: {{run.finishedAt ? run.finishedAt|date('U') : "null"}}
			};
		</script>
	{% endif %}
	
{% endblock %}

{% block title %}
	Bienvenu sur running-maps !
{% endblock %}

{% block body %}
    <section class="header">
        <a href="{{path('app_map_index')}}">
			<img src="{{ asset("assets/images/logo-reduit.svg") }}" alt="">
		</a>
		{% if is_granted('ROLE_RUNNER') %}
			<a href="{{path("app_runner")}}"><div class="profile"><i class="fa-solid fa-user"></i><p>Profil</p></div></a>
		{% elseif is_granted('ROLE_ADMIN') %}
			<a href="{{path("app_admin_index")}}"><div class="profile"><i class="fa-solid fa-user"></i><p>Admin</p></div></a>
		{% else %}
			<a href="{{path("app_login")}}"><div class="profile"><i class="fa-solid fa-user"></i><p>Connexion</p></div></a>
		{% endif %}
    </section>

    <section class="activeRun">
	{# if the there is a run, then render it with infos #}
	{% if run %}
		<div class="activeRun__name">
			{% if not run.finishedAt and run.runDate|date("U") <= "now"|date("U") %}
				<h2>Course
					{{run.name}}
				</h2>
				<span class="run__live">LIVE</span>
			{% elseif not run.finishedAt and run.runDate|date("U") > "now"|date("U") %}
				<h2>Course
					{{run.name}}
				</h2>
				<span class="run__future">A VENIR</span>
			{% else %}
				<h2>Course
					{{run.name}}
				</h2>
				<span class="run__finished">COMPLETE</span>
			{% endif %}
		</div>
		<div class="croix activeCross">
			<span></span>
		</div>
		
		<div class="primaryMap">
			<div id="map"></div>
		</div>

		<div class="activeRun__infos">
			<h3>{{run.name}}</h3>
			<p>Debut de course : le
				{{run.runDate|date("d F, Y \à H:i:s")}}</p>
			<p>Fin de course :
				{{run.finishedAt ? run.finishedAt|date("d F, Y \à H:i:s") : "la course n'est pas terminée."}}</p>
		</div>
		<div class="activeRun__buttons">
			<a href="{{path('app_map_id', {'id': run.id})}}" class="p-button" style="font-size:1.75rem;">Voir la course</a>
			{% if is_granted('ROLE_ADMIN') and not run.finishedAt and run.runDate|date() < "now"|date() %}
				<form action="{{path("app_admin_run_finish", {"id": run.id})}}" method="POST" onsubmit="return confirm('Etes-vous sur de vouloir terminer cette course ?');">
					<button type="submit" class="p-button endButton" style="font-size:1.75rem;">Terminer la course</button>
				</form>
			{% endif %}
		</div>
	{# if there is no run, render this message #}
	{% else %}
		<p>Aucune course n'est enregistrée à l'instant. Veullez revenir plus tard.</p>
	{% endif %}
</section>
<section class="upcomingRuns">
	<h2>Courses à venir</h2>
	<div class="runs__container">
		{% for run in upcomingRuns %}
			<div class="run">
				<div class="activeRun__infos">
					<h3>{{run.name}}</h3>
					<p>{{run.runDate|date("d F, Y \à H:i:s")}}</p>
				</div>
				<div class="allRuns__buttons">
					<a href="{{path("app_map_id", {"id": run.id})}}" class="s-button" style="font-size:24px; margin-top:18px;">+ d'infos</a>
				</div>
			</div>
		{% else %}
			<p>Aucune course n'est programmée.</p>
		{% endfor %}
	</div>
</section>
<section class="pastRuns">
	<h2>Courses passées</h2>
	<div class="runs__container">
		{% for run in pastRuns %}
			<div class="run">
				<div class="activeRun__infos">
					<h3>{{run.name}}</h3>
					<p>{{run.runDate|date("d F, Y \à H:i:s")}}</p>
				</div>
				<div class="allRuns__buttons">
					<a href="{{path("app_map_id", {"id": run.id})}}" class="s-button" style="font-size:24px; margin-top:18px;">+ d'infos</a>
				</div>
			</div>
		{% else %}
			<p>Aucune course n'est programmée.</p>
		{% endfor %}
	</div>
</section>
<div class="nav">
	<ul>
		<li class="nav__list ">
			<a href="{{path('app_map_id')}}">
				<span class="nav__list--icon">
					<i class="fa-solid fa-person-running"></i>
				</span>
				<span class="nav__list--text">Course</span>
			</a>
		</li>
		<li class="nav__list active">
			<a href="{{ path('app_map_index') }}">
				<span class="nav__list--icon">
					<i class="fa-solid fa-house"></i>
				</span>
				<span class="nav__list--text">Accueil</span>
			</a>
		</li>
		<li class="nav__list">
			{% if is_granted('ROLE_RUNNER') %}
				<a href="{{path("app_runner")}}">
					<span class="nav__list--icon">
						<i class="fa-solid fa-user"></i>
					</span>
					<span class="nav__list--text">Profil</span>
				</a>
			{% elseif is_granted('ROLE_ADMIN') %}
				<a href="{{path("app_admin_index")}}">
					<span class="nav__list--icon">
						<i class="fa-solid fa-user"></i>
					</span>
					<span class="nav__list--text">Profil</span>
				</a>
			{% else %}
				<a href="{{path("app_login")}}">
					<span class="nav__list--icon">
						<i class="fa-solid fa-user"></i>
					</span>
					<span class="nav__list--text">Profil</span>
				</a>
			{% endif %}
		</li>
		<div class="indicator"></div>
	</ul>
</div>
{% endblock %}

templates/map/show.html.twig
{% extends 'map.html.twig' %}

{% block title %}{{run.name}}{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="{{ asset("assets/css/font.css") }}">
<link rel="stylesheet" href="{{ asset("assets/css/base.css") }}">
<link rel="stylesheet" href="{{ asset("assets/css/navbar.css") }}">
<link rel="stylesheet" href="{{ asset("assets/css/indexMap.css") }}">
<link rel="stylesheet" href="{{ asset("assets/css/inputRange.css") }}">
{% endblock %}

{% block javascripts %}
        <script src="{{ asset("assets/js/navbar.js") }}"></script>
        <script>
            const Run = {
                id: {{run.id}}, name: "{{run.name}}", created_at: {{run.createdAt|date('U')}}, map: "{{run.map}}", date: {{run.runDate|date('U')}}, finished_at: {{run.finishedAt ? run.finishedAt|date('U') : "null"}}
            };
            window.addEventListener('DOMContentLoaded', async () => {
                //run progress showcase with range slider
                let timer;
                let timestamp_input = document.querySelector('.time-choice');
                if(!timestamp_input) return;
                timestamp_input.value = 0;
                timestamp_input.addEventListener('input', function()  {
                    clearTimeout(timer);
                    //fetch only half a second after selecting
                    timer = setTimeout( async () => {
                        await App.updateMarkers(await GetRunnersInfo(this.value));
                    }, 500);
                });
            });
        </script>
{% endblock %}

{% block body %}
<div class="map">
	<div id="map"></div>
	<a href="{{ path('app_map_index') }}" class="logo"><img src="{{ asset("assets/images/logo-reduit.svg") }}" alt=""></a>
</div>
<div class="map__date">
    <div>
		<p>Debut de course :
			{{run.runDate|date('d F, Y \à H:i:s')}}</p>
		<p>Fin de course :
			{{run.finishedAt ? run.finishedAt|date('d F, Y \à H:i:s') : "la course n'est pas terminée."}}</p>
	</div>
    <span>
		<a href="#stats" class="p-button" style="font-size:1.5rem">Voir les participants</a>
	</span>
</div>
{% if run.finishedAt %}
<div class="time-choice__container">
	<h2>Historique de la course</h2>
    <div>
		<input class="time-choice" type="range" value="{{run.runDate|date('U')}}" min="{{run.runDate|date('U')}}" max="{{run.finishedAt|date('U')}}">
	</div>
</div>
{% endif %}
<section id="stats">
    <h2>Participants :</h2>
    <div class="participants">
        {% for runner in run.getRunners() %}
            <div class="participant">
                <img src="{{ asset("assets/users/" ~ runner.picture) }}" alt="">
                <p>{{runner.login}}</p>
            </div>
        {% endfor %}
    </div>
</section>
<div class="nav">
<ul>
	<li class="nav__list active">
		<a href="{{path('app_map_id')}}">
			<span class="nav__list--icon">
				<i class="fa-solid fa-person-running"></i>
			</span>
			<span class="nav__list--text">Courses</span>
		</a>
	</li>
	<li class="nav__list">
		<a href="{{ path('app_map_index') }}">
			<span class="nav__list--icon">
				<i class="fa-solid fa-house"></i>
			</span>
			<span class="nav__list--text">Accueil</span>
		</a>
	</li>
	<li class="nav__list">
		{% if is_granted('ROLE_RUNNER') %}
			<a href="{{path("app_runner")}}">
				<span class="nav__list--icon">
					<i class="fa-solid fa-user"></i>
				</span>
				<span class="nav__list--text">Profil</span>
			</a>
		{% elseif is_granted('ROLE_ADMIN') %}
			<a href="{{path("app_admin_index")}}">
				<span class="nav__list--icon">
					<i class="fa-solid fa-user"></i>
				</span>
				<span class="nav__list--text">Profil</span>
			</a>
		{% else %}
			<a href="{{path("app_login")}}">
				<span class="nav__list--icon">
					<i class="fa-solid fa-user"></i>
				</span>
				<span class="nav__list--text">Profil</span>
			</a>
		{% endif %}
	</li>
	<div class="indicator"></div>
</ul>
</div>


{% endblock %}