src/Entity/Run.php
<?php

namespace App\Entity;

use App\Repository\RunRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\JoinTable;

#[ORM\Entity(repositoryClass: RunRepository::class)]
class Run
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(length: 255)]
    private ?string $map = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $run_date = null;

    #[ORM\ManyToMany(targetEntity: Runner::class, inversedBy: 'run')]
    private Collection $runner;

    #[ORM\OneToMany(mappedBy: 'run', targetEntity: RunJoinRequest::class, orphanRemoval: true)]
    private Collection $runJoinRequests;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $finished_at = null;

    public function __construct()
    {
        $this->runner = new ArrayCollection();
        $this->created_at = new \DateTimeImmutable();
        $this->runJoinRequests = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getMap(): ?string
    {
        return $this->map;
    }

    public function setMap(string $map): self
    {
        $this->map = $map;

        return $this;
    }

    public function getRunDate(): ?\DateTimeInterface
    {
        return $this->run_date;
    }

    public function setRunDate(\DateTimeInterface $run_date): self
    {
        $this->run_date = $run_date;

        return $this;
    }

    /**
     * @return Collection<int, runner>
     */
    public function getRunners(): Collection
    {
        return $this->runner;
    }

    public function addRunner(Runner $runner): self
    {
        if (!$this->runner->contains($runner)) {
            $this->runner->add($runner);
        }

        return $this;
    }

    public function removeRunner(Runner $runner): self
    {
        $this->runner->removeElement($runner);

        return $this;
    }

    /**
     * @return Collection<int, RunJoinRequest>
     */
    public function getRunJoinRequests(): Collection
    {
        return $this->runJoinRequests;
    }

    public function addRunJoinRequest(RunJoinRequest $runJoinRequest): self
    {
        if (!$this->runJoinRequests->contains($runJoinRequest)) {
            $this->runJoinRequests->add($runJoinRequest);
            $runJoinRequest->setRun($this);
        }

        return $this;
    }

    public function removeRunJoinRequest(RunJoinRequest $runJoinRequest): self
    {
        if ($this->runJoinRequests->removeElement($runJoinRequest)) {
            // set the owning side to null (unless already changed)
            if ($runJoinRequest->getRun() === $this) {
                $runJoinRequest->setRun(null);
            }
        }

        return $this;
    }

    public function getFinishedAt(): ?\DateTimeImmutable
    {
        return $this->finished_at;
    }

    public function setFinishedAt(?\DateTimeImmutable $finished_at): self
    {
        $this->finished_at = $finished_at;

        return $this;
    }
}

src/Entity/Runner.php
<?php

namespace App\Entity;

use App\Repository\RunnerRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: RunnerRepository::class)]
class Runner implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $login = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $picture = null;

    #[ORM\OneToMany(mappedBy: 'Runner', targetEntity: Coordinates::class)]
    private Collection $coords;

    #[ORM\ManyToMany(targetEntity: Run::class, mappedBy: 'runner')]
    private Collection $runs;

    #[ORM\OneToMany(mappedBy: 'runner', targetEntity: RunJoinRequest::class, orphanRemoval: true)]
    private Collection $runJoinRequests;

    public function __construct()
    {
        $this->coords = new ArrayCollection();
        $this->runs = new ArrayCollection();
        $this->runJoinRequests = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLogin(): ?string
    {
        return $this->login;
    }

    public function setLogin(string $login): self
    {
        $this->login = $login;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->login;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        $roles[] = 'ROLE_RUNNER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    /**
     * @return Collection<int, Coordinates>
     */
    public function getCoords(): Collection
    {
        return $this->coords;
    }

    public function addCoord(Coordinates $coord): self
    {
        if (!$this->coords->contains($coord)) {
            $this->coords->add($coord);
            $coord->setRunner($this);
        }

        return $this;
    }

    public function removeCoord(Coordinates $coord): self
    {
        if ($this->coords->removeElement($coord)) {
            // set the owning side to null (unless already changed)
            if ($coord->getRunner() === $this) {
                $coord->setRunner(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Run>
     */
    public function getRuns(): Collection
    {
        return $this->runs;
    }

    public function addRun(Run $run): self
    {
        if (!$this->runs->contains($run)) {
            $this->runs->add($run);
            $run->addRunner($this);
        }

        return $this;
    }

    public function removeRun(Run $run): self
    {
        if ($this->runs->removeElement($run)) {
            $run->removeRunner($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, RunJoinRequest>
     */
    public function getRunJoinRequests(): Collection
    {
        return $this->runJoinRequests;
    }
    
    public function addRunJoinRequest(RunJoinRequest $runJoinRequest): self
    {
        if (!$this->runJoinRequests->contains($runJoinRequest)) {
            $this->runJoinRequests->add($runJoinRequest);
            $runJoinRequest->setRunner($this);
        }

        return $this;
    }

    public function removeRunJoinRequest(RunJoinRequest $runJoinRequest): self
    {
        if ($this->runJoinRequests->removeElement($runJoinRequest)) {
            // set the owning side to null (unless already changed)
            if ($runJoinRequest->getRunner() === $this) {
                $runJoinRequest->setRunner(null);
            }
        }

        return $this;
    }
}

src/Form/RunnerType.php
<?php

namespace App\Form;

use App\Entity\Runner;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RunnerType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('login')
            ->add('password')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Runner::class,
        ]);
    }
}

src/Controller/RunnerController.php
<?php

namespace App\Controller;

use App\Entity\Run;
use App\Entity\Runner;
use App\Entity\RunJoinRequest;
use App\Repository\RunRepository;
use App\Repository\RunnerRepository;
use App\Repository\RunJoinRequestRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;

#[Route('/runner')]
class RunnerController extends AbstractController
{
    #[Route('/', name: 'app_runner')]
    public function index(RunRepository $runRepository, RunnerRepository $runnerRepository): Response
    {
        $joinRequests = $runnerRepository->find($this->getUser())->getRunJoinRequests();
        $runsFromRequests = array();
        foreach ($joinRequests as $r) {
            $runsFromRequests[] = $r->getRun();
        }
        
        return $this->render('runner/index.html.twig', [
            'runs' => $runRepository->findAll(),
            'user' => $this->getUser(),
            'requests' => $runsFromRequests
        ]);
    }
    
    #[Route('/{id}', name: 'app_runner_profile')]
    public function profile(Runner $runner): Response
    {
        return $this->render('runner/profile.html.twig', [
            'connectedUser' => $this->getUser() == $runner,
            'runner' => $runner,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_runner_edit', methods: ['GET', 'POST'])]
    /**
     * Edit runner's profile picture
     *
     * @param Request $request
     * @param Runner $runner
     * @param RunnerRepository $runnerRepository
     * @param SluggerInterface $slugger
     * @return Response
     */   
    public function edit(Request $request, Runner $runner, RunnerRepository $runnerRepository, SluggerInterface $slugger): Response
    {
        // $form = $this->createForm(RunnerType::class, $runner);
        $form = $this->createFormBuilder($runner)
            ->add('picture', FileType::class, [
                'mapped' => false
            ])
            ->getForm();
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $pictureFile = $form->get('picture')->getData();
            if ($pictureFile) {
                $originalFilename = pathinfo($pictureFile->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename . '-' . uniqid() . '.' . $pictureFile->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $pictureFile->move(
                        $this->getParameter('pfp_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }
                $runner->setPicture($newFilename);
            }
            $runnerRepository->save($runner, true);

            return $this->redirectToRoute('app_runner_profile', ["id" => $runner->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->render('runner/edit.html.twig', [
            'runner' => $runner,
            'form' => $form,
        ]);
    }

    #[Route('/run/{id}', name: 'app_runner_run')]
    public function run(Run $run): Response
    {
        return $this->render('runner/run.html.twig', [
            'run' => $run
        ]);
    }

    #[Route('/participate/{id}', name: 'app_runner_participate')]
    public function participate(RunJoinRequestRepository $runJoinRequestRepository, Run $run): RedirectResponse
    {
        $runJoinRequest = new RunJoinRequest();
        $runJoinRequest
            ->setRunner($this->getUser())
            ->setRun($run);
        $runJoinRequestRepository->save($runJoinRequest, true);
        return $this->redirectToRoute('app_runner');
    }
}

templates/runner/_form.html.twig
{% block stylesheets %}
<link rel="stylesheet" href="{{ asset("assets/css/font.css") }}">
<link rel="stylesheet" href="{{ asset("assets/css/base.css") }}">
<link rel="stylesheet" href="{{ asset("assets/css/runnerForm.css") }}">
{% endblock %}
{{ form_start(form) }}
    <img src="{{ asset("assets/images/logo-complet.png") }}" alt="" class="logo">
    <div>
        <h1>{{ h1_label|default('') }}</h1>
        {{ form_widget(form) }}
        <button class="btn">{{ button_label|default('Créer') }}</button>
        <a href="{{ path('app_runner_profile', {id: app.user.id}) }}" class="retour">Retourner à l'accueil</a>
    </div>
    
{{ form_end(form) }}
<img src="{{ asset("assets/images/createLogin-background.png") }}" alt="" class="bg-img">

templates/runner/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier la photo de profil{% endblock %}

{% block body %}
    {{ include('runner/_form.html.twig', {'button_label': 'Modifier'}, {'h1_label': 'Modifier le profil d\'un coureur'}) }}
{% endblock %}

templates/runner/index.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
<link rel="stylesheet" href="{{ asset("assets/css/font.css") }}">
<link rel="stylesheet" href="{{ asset("assets/css/base.css") }}">
<link rel="stylesheet" href="{{ asset("assets/css/navbar.css") }}">
<link rel="stylesheet" href="{{ asset("assets/css/profile.css") }}">
{% endblock %}
{% block title %}Profil -
	{{user.login}}
{% endblock %}

{% block body %}
	<a href="{{ path('app_runner_profile', {'id': user.id}) }}" class="p-button center">Voir mon profil</a>
	<section class="runs__container">
        {% for run in runs %}
		<div class="runs">
			<h3>Course : {{run.name}}</h3>
			{# if requested to join #}
			{% if run in requests %}
				<p class="progress">Demande en cours</p>
				{# if request accepted #}
			{% elseif user in run.getRunners %}
				<span>Commence le {{run.runDate|date("d M, Y \à H:i:s")}}</span>
				<div class="runs__buttons">
					<p class="accepted">Participation acceptée</p>
					<a class="request" href="{{path('app_runner_run', {id: run.id})}}">Courir</a>
				</div>
			{# if none above then able to request to participate #}
			{% else %}
				<a class="request" href="{{path('app_runner_participate', {'id': run.id})}}">Demander la participation</a>
			{% endif %}
		</div>
		{% else %}
			<p>Aucune course est disponible en ce moment.</p>
		{% endfor %}
	</section>
	<div class="nav">
            <ul>
                <li class="nav__list ">
                    <a href="{{path('app_map_id')}}" >
                        <span class="nav__list--icon"><i class="fa-solid fa-person-running"></i></span>
                        <span class="nav__list--text">Course</span>
                    </a>
                </li>
                <li class="nav__list ">
                    <a href="{{ path('app_map_index') }}">
                        <span class="nav__list--icon"><i class="fa-solid fa-house"></i></span>
                        <span class="nav__list--text">Accueil</span>
                    </a>
                </li>
                <li class="nav__list active">
                    <a href="/runner/">
                        <span class="nav__list--icon"><i class="fa-solid fa-user"></i></span>
                        <span class="nav__list--text">Profil</span>
                    </a>
                </li>
                <div class="indicator"></div>
            </ul>	
	    </div>
		<div class="logout">
			<p>Vous êtes connecté en tant que {{ app.user.userIdentifier }}</p>
            <a href="{{ path('app_logout') }}">Me déconnecter</a>
        </div>
		{% block javascripts %}
			<script src="https://kit.fontawesome.com/faa5ea95e9.js" crossorigin="anonymous"></script>
        	<script src="{{ asset("assets/js/navbar.js") }}"></script>
		{% endblock %}
{% endblock %}

templates/runner/profile.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
<link rel="stylesheet" href="{{ asset("assets/css/profile.css") }}">
<link rel="stylesheet" href="{{ asset("assets/css/font.css") }}">
<link rel="stylesheet" href="{{ asset("assets/css/base.css") }}">
<link rel="stylesheet" href="{{ asset("assets/css/navbar.css") }}">
{% endblock %}
{% block title %}{{runner.login}}{% endblock %}

{% block body %}
	<section class="header">
        <a href="{{path('app_map_index')}}">
			<img src="{{ asset("assets/images/logo-reduit.svg") }}" alt="">
		</a>
        <a href="/runner/"><div class="header__profile"><img src="{{asset("/assets/users/" ~ runner.picture)}}" alt=""></div></a>
    </section>
	<section class="profile">
		<h1 class="profile__title"><span>Bienvenue</span> sur
			{{(connectedUser) ? 'votre' : 'le'}}
			profil
			<span>{{runner.login}}</span></h1>
		<div class="profile__div">
			{# shows different text depending on user seeing the page #}
			<h2 class="profile__lastRun--title">{{(connectedUser) ? 'Vos dernières courses' : 'Les dernieres courses de ' ~ runner.login}}</h2>
			<div class="profile__lastRun">
				{% for run in runner.getRuns %}	
					<div class="profile__lastRun--block">
						<p><span>{{run.name}}</span></p>
						{% if run.runDate|date() < "now"|date() and not run.finishedAt %}
							<p>La course est en live.</p>
						{% elseif run.runDate|date() >= "now"|date() %}
							<p>Commence le {{run.runDate|date("d M Y, à    H:i:s")}}</p>
						{% elseif run.finishedAt %}
							<p>Faite le {{run.runDate|date("d M Y, à    H:i:s")}}</p>
						{% endif %}
					</div>
						{% else %}
						<p>Aucune course.</p>
				{% endfor %}
			</div>
	</section>
    {# <section class="profile">
        <h2>{{(connectedUser) ? 'Vos statistiques' : 'Les statistiques de ' ~ runner.login}}</h2>
    </section> #}
	{% if connectedUser %}
		<section class="profile profile__modifier">
			<h2>Modifier la photo de profil</h2>
			<div class="profile__modifier--div">
				<span class="modifier"><img src="{{asset("/assets/users/" ~ runner.picture)}}" alt=""><p>Photo actuelle</p></span>
				<a href="{{path('app_runner_edit', {'id': app.user.id})}}" class="modifier"><img src="{{ asset("assets/images/ajout.svg") }}" alt=""><p>Modifier la photo</p></a>
			</div>
		</section>
	{% endif %}
	
	 <div class="nav">
            <ul>
                <li class="nav__list ">
                    <a href="{{path('app_map_id')}}" >
                        <span class="nav__list--icon"><i class="fa-solid fa-person-running"></i></span>
                        <span class="nav__list--text">Course</span>
                    </a>
                </li>
                <li class="nav__list ">
                    <a href="{{ path('app_map_index') }}">
                        <span class="nav__list--icon"><i class="fa-solid fa-house"></i></span>
                        <span class="nav__list--text">Accueil</span>
                    </a>
                </li>
                <li class="nav__list active">
                    <a href="/runner/">
                        <span class="nav__list--icon"><i class="fa-solid fa-user"></i></span>
                        <span class="nav__list--text">Profil</span>
                    </a>
                </li>
                <div class="indicator"></div>
            </ul>	
	    </div>
    
    {% block javascripts %}
			<script src="https://kit.fontawesome.com/faa5ea95e9.js" crossorigin="anonymous"></script>
		    <script src="{{ asset("assets/js/navbar.js") }}"></script>
	{% endblock %}
{% endblock %}

templates/runner/run.html.twig
{% extends 'base.html.twig' %}

{% block title %}Running -
	{{app.user.login}}
{% endblock %}

{% block body %}
	<div>
        Tu cours sur la course {{run.name}}
	</div>
    <script defer>
        const UserId = {{app.user.id}};
        const RunId = {{run.id}};
        const RunDate = {{run.runDate|date('U')}};
    </script>
    <script src="{{ asset('/assets/js/runner.js') }}" defer></script>
{% endblock %}